# Generated by Django 3.0.14 on 2023-02-17 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimestampedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='routine.TimestampedModel')),
                ('routine_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('MIRACLE', '기상 관련'), ('HOMEWORK', '숙제 관련')], max_length=10)),
                ('goal', models.CharField(max_length=500)),
                ('is_alarm', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_set', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('routine.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='RoutineResult',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='routine.TimestampedModel')),
                ('routine_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('NOT', '안함'), ('TRY', '시도'), ('DONE', '완료')], max_length=5)),
                ('is_deleted', models.BooleanField(default=False)),
                ('routine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_result_set', to='routine.Routine')),
            ],
            bases=('routine.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='routine.TimestampedModel')),
                ('day', models.CharField(choices=[('MO', '월요일'), ('TU', '화요일'), ('WE', '수요일'), ('TH', '목요일'), ('FR', '금요일'), ('SA', '토요일'), ('SU', '일요일')], max_length=2)),
                ('routine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_day_set', to='routine.Routine')),
            ],
            bases=('routine.timestampedmodel',),
        ),
    ]
