# Generated by Django 3.0.14 on 2023-02-27 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimestampedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='routine.TimestampedModel')),
                ('routine_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('MIRACLE', 'MIRACLE(기상 관련)'), ('HOMEWORK', 'HOMEWORK(숙제 관련)')], max_length=10)),
                ('goal', models.CharField(max_length=500)),
                ('is_alarm', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_set', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('routine.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='RoutineResult',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='routine.TimestampedModel')),
                ('routine_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('NOT', 'NOT(안함)'), ('TRY', 'TRY(시도)'), ('DONE', 'DONE(완료)')], default='NOT', max_length=5)),
                ('is_deleted', models.BooleanField(default=False)),
                ('routine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_result_set', to='routine.Routine')),
            ],
            bases=('routine.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='routine.TimestampedModel')),
                ('day', models.CharField(choices=[('MON', '월요일'), ('TUE', '화요일'), ('WED', '수요일'), ('THU', '목요일'), ('FRI', '금요일'), ('SAT', '토요일'), ('SUN', '일요일')], max_length=3)),
                ('routine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_day_set', to='routine.Routine')),
            ],
            bases=('routine.timestampedmodel',),
        ),
    ]
